language : python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-lxml
install:
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install .
script:
  - nosetests -s
