language : python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev
install:
  - pip install lxml              
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install .
script:
  - nosetests -s --with-coverage --cover-erase --cover-package=autodl
  - flake8 autodl/utils.py  
  - flake8 tests/utils_tests.py
