language : python
python:
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y python-dev
install:
  - pip install lxml              
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - pip install .
before_script:
  - sudo mkdir /etc/autodl
  - sudo cp conf/autodl_config.json.sample /etc/autodl/autodl_config.json
  - sudo chmod -r 755 /etc/autodl

script:
  - nosetests -s
